// [LAW:one-source-of-truth] versions.json is the sole source of version data;
// this module is a pure projection of it to HTML. No second representation.
// [LAW:dataflow-not-control-flow] Same operations run every call. Empty manifest
// and missing commits[] are encoded in the data path (array iteration over [],
// nullish coalescing to []) — never in conditional skips of operations.
// [LAW:single-enforcer] All user-controlled string interpolation MUST go through
// escapeHtml(). No raw ${userData} is permitted anywhere in the rendered output.

import type { Manifest, ManifestEntry, CommitInfo } from './types.js';

export interface RepoMeta {
  owner: string;
  repo: string;
}

export function escapeHtml(raw: string): string {
  return raw
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function renderCommitDetailsBlock(commits: CommitInfo[]): string {
  // [LAW:dataflow-not-control-flow] data-driven string selection: empty list -> empty string,
  // populated list -> details element. The concatenation in the caller always runs.
  const isEmpty = commits.length === 0;
  const placeholder = `<details><summary>${commits.length} commit${commits.length === 1 ? '' : 's'}</summary></details>`;
  return isEmpty ? '' : placeholder;
}

function renderVersionCard(entry: ManifestEntry): string {
  // [LAW:single-enforcer] every interpolation of user-controlled fields passes through escapeHtml.
  const commits: CommitInfo[] = entry.commits ?? [];
  const detailsBlock = renderCommitDetailsBlock(commits);
  return (
    `<article class="version">` +
    `<h2>${escapeHtml(entry.version)}</h2>` +
    `<p class="meta">ref: <code>${escapeHtml(entry.ref)}</code></p>` +
    detailsBlock +
    `</article>`
  );
}

function renderEmptyState(): string {
  return `<article class="empty"><h2>No versions deployed yet</h2><p>Deploy a version to see it here.</p></article>`;
}

export function renderIndexHtml(manifest: Manifest, repoMeta: RepoMeta): string {
  const count = manifest.versions.length;
  const versionWord = count === 1 ? 'version' : 'versions';
  const subtitleText =
    count === 0 ? 'No versions deployed yet' : `${count} ${versionWord} deployed`;
  const title = `${repoMeta.owner}/${repoMeta.repo} \u2014 Deployed Versions`;
  const heading = `${repoMeta.owner}/${repoMeta.repo}`;
  // [LAW:dataflow-not-control-flow] Purity: the "generated at" signal is derived
  // from the manifest (newest entry's timestamp) rather than wall clock, so
  // renderIndexHtml is a total pure function of its inputs. Empty manifest -> empty.
  // [Rule 1 - Bug] Wall-clock Date.now() broke determinism (purity test failed under
  // concurrent scheduling when two calls crossed a millisecond boundary).
  const generatedAt = count === 0 ? '' : manifest.versions[0].timestamp;

  // [LAW:dataflow-not-control-flow] data chooses which string fills the section;
  // the section element is always emitted with a string child.
  const bodyContent =
    count === 0
      ? renderEmptyState()
      : manifest.versions.map(renderVersionCard).join('');

  return (
    `<!doctype html>\n` +
    `<html lang="en">\n` +
    `<head>\n` +
    `<meta charset="utf-8">\n` +
    `<meta name="viewport" content="width=device-width, initial-scale=1">\n` +
    `<title>${escapeHtml(title)}</title>\n` +
    `<style>/* Plan 03-02 fills this in */</style>\n` +
    `</head>\n` +
    `<body>\n` +
    `<main>\n` +
    `<header>\n` +
    `<h1>${escapeHtml(heading)}</h1>\n` +
    `<p class="subtitle">${escapeHtml(subtitleText)}</p>\n` +
    `</header>\n` +
    `<section class="versions">${bodyContent}</section>\n` +
    `<footer>Generated by gh-pages-multiplexer \u00b7 ${escapeHtml(generatedAt)}</footer>\n` +
    `</main>\n` +
    `</body>\n` +
    `</html>\n`
  );
}
