import { describe, it, expect } from 'vitest';
import { renderIndexHtml, escapeHtml } from '../src/index-renderer.js';
import type { Manifest, ManifestEntry } from '../src/types.js';

function entry(partial: Partial<ManifestEntry> & { version: string }): ManifestEntry {
  return {
    version: partial.version,
    ref: partial.ref ?? `refs/tags/${partial.version}`,
    sha: partial.sha ?? '0000000000000000000000000000000000000000',
    timestamp: partial.timestamp ?? '2026-04-06T12:00:00.000Z',
    commits: partial.commits,
  };
}

const repo = { owner: 'acme', repo: 'widgets' };

describe('index-renderer skeleton', () => {
  it('is a pure function (deterministic, no I/O between identical calls)', () => {
    const m: Manifest = { schema: 2, versions: [entry({ version: 'v1.0.0' })] };
    const a = renderIndexHtml(m, repo);
    const b = renderIndexHtml(m, repo);
    expect(a).toBe(b);
  });

  it('renders empty manifest with locked empty-state copy', () => {
    const out = renderIndexHtml({ schema: 2, versions: [] }, repo);
    expect(out.toLowerCase().startsWith('<!doctype html')).toBe(true);
    expect(out).toContain('No versions deployed yet');
    expect(out).toContain('Deploy a version to see it here.');
  });

  it('contains <html lang="en"> and exact title with em-dash', () => {
    const out = renderIndexHtml({ schema: 2, versions: [] }, repo);
    expect(out).toContain('<html lang="en"');
    expect(out).toContain('<title>acme/widgets \u2014 Deployed Versions</title>');
  });

  it('renders an h1 with the repo heading', () => {
    const out = renderIndexHtml({ schema: 2, versions: [] }, repo);
    expect(out).toMatch(/<h1[^>]*>acme\/widgets<\/h1>/);
  });

  it('uses singular subtitle copy for exactly 1 version', () => {
    const out = renderIndexHtml(
      { schema: 2, versions: [entry({ version: 'v1.0.0' })] },
      repo,
    );
    expect(out).toContain('1 version deployed');
    expect(out).not.toContain('1 versions deployed');
  });

  it('uses plural subtitle copy for 3 versions', () => {
    const out = renderIndexHtml(
      {
        schema: 2,
        versions: [
          entry({ version: 'v1.0.0' }),
          entry({ version: 'v1.1.0' }),
          entry({ version: 'v1.2.0' }),
        ],
      },
      repo,
    );
    expect(out).toContain('3 versions deployed');
  });

  it('legacy schema-1 entry (commits undefined) renders no <details> element', () => {
    const out = renderIndexHtml(
      { schema: 1, versions: [entry({ version: 'v1.0.0' })] },
      repo,
    );
    expect(out).toContain('v1.0.0');
    expect(out).toContain('refs/tags/v1.0.0');
    expect(out).not.toContain('<details');
  });

  it('schema-2 entry with empty commits[] renders no <details> element', () => {
    const out = renderIndexHtml(
      { schema: 2, versions: [entry({ version: 'v1.0.0', commits: [] })] },
      repo,
    );
    expect(out).not.toContain('<details');
  });

  it('escapeHtml maps all HTML metacharacters', () => {
    expect(escapeHtml('&')).toBe('&amp;');
    expect(escapeHtml('<')).toBe('&lt;');
    expect(escapeHtml('>')).toBe('&gt;');
    expect(escapeHtml('"')).toBe('&quot;');
    expect(escapeHtml("'")).toBe('&#39;');
    expect(escapeHtml('<script>alert("x")</script>')).toBe(
      '&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;',
    );
  });

  it('escapes user-controlled version names in output', () => {
    const out = renderIndexHtml(
      { schema: 2, versions: [entry({ version: 'v1<script>' })] },
      repo,
    );
    expect(out).toContain('v1&lt;script&gt;');
    expect(out).not.toContain('v1<script>');
  });

  it('footer contains the freshness signal', () => {
    const out = renderIndexHtml({ schema: 2, versions: [] }, repo);
    expect(out).toContain('Generated by gh-pages-multiplexer');
  });
});
