import { describe, it, expect } from 'vitest';
import { HtmlValidate } from 'html-validate';
import { renderIndexHtml, renderRedirectHtml, escapeHtml } from '../src/index-renderer.js';
import type { Manifest, ManifestEntry, CommitInfo } from '../src/types.js';

function entry(partial: Partial<ManifestEntry> & { version: string }): ManifestEntry {
  return {
    version: partial.version,
    ref: partial.ref ?? `refs/tags/${partial.version}`,
    sha: partial.sha ?? '0000000000000000000000000000000000000000',
    timestamp: partial.timestamp ?? '2026-04-06T12:00:00.000Z',
    commits: partial.commits,
  };
}

function commit(partial: Partial<CommitInfo> & { sha: string }): CommitInfo {
  return {
    sha: partial.sha,
    author_name: partial.author_name ?? 'Alice',
    author_email: partial.author_email ?? 'alice@example.com',
    message: partial.message ?? 'initial commit',
    timestamp: partial.timestamp ?? '2026-04-05T10:00:00.000Z',
  };
}

const repo = { owner: 'acme', repo: 'widgets' };

const validator = new HtmlValidate({
  extends: ['html-validate:recommended'],
  rules: {
    'no-inline-style': 'off',
  },
});

async function assertValidHtml(html: string): Promise<void> {
  const report = await validator.validateString(html);
  if (!report.valid) {
    const messages = report.results.flatMap((r) =>
      r.messages.map((m) => `${m.ruleId}: ${m.message} @ line ${m.line}`),
    );
    throw new Error(`html-validate failed:\n${messages.join('\n')}`);
  }
}

describe('index-renderer skeleton', () => {
  it('is a pure function (deterministic, no I/O between identical calls)', () => {
    const m: Manifest = { schema: 2, versions: [entry({ version: 'v1.0.0' })] };
    const a = renderIndexHtml(m, repo);
    const b = renderIndexHtml(m, repo);
    expect(a).toBe(b);
  });

  it('renders empty manifest with locked empty-state copy', () => {
    const out = renderIndexHtml({ schema: 2, versions: [] }, repo);
    expect(out.toLowerCase().startsWith('<!doctype html')).toBe(true);
    expect(out).toContain('No versions deployed yet');
    expect(out).toContain('Deploy a version to see it here.');
  });

  it('contains <html lang="en"> and exact title with em-dash', () => {
    const out = renderIndexHtml({ schema: 2, versions: [] }, repo);
    expect(out).toContain('<html lang="en"');
    expect(out).toContain('<title>acme/widgets \u2014 Deployed Versions</title>');
  });

  it('renders an h1 with the repo heading', () => {
    const out = renderIndexHtml({ schema: 2, versions: [] }, repo);
    expect(out).toMatch(/<h1[^>]*>[\s\S]*acme\/widgets[\s\S]*<\/h1>/);
  });

  it('uses singular subtitle copy for exactly 1 version', () => {
    const out = renderIndexHtml(
      { schema: 2, versions: [entry({ version: 'v1.0.0' })] },
      repo,
    );
    expect(out).toContain('1 version deployed');
    expect(out).not.toContain('1 versions deployed');
  });

  it('uses plural subtitle copy for 3 versions', () => {
    const out = renderIndexHtml(
      {
        schema: 2,
        versions: [
          entry({ version: 'v1.0.0' }),
          entry({ version: 'v1.1.0' }),
          entry({ version: 'v1.2.0' }),
        ],
      },
      repo,
    );
    expect(out).toContain('3 versions deployed');
  });

  it('legacy schema-1 entry (commits undefined) renders no <details> element', () => {
    const out = renderIndexHtml(
      { schema: 1, versions: [entry({ version: 'v1.0.0' })] },
      repo,
    );
    expect(out).toContain('v1.0.0');
    expect(out).toContain('refs/tags/v1.0.0');
    expect(out).not.toContain('<details');
  });

  it('schema-2 entry with empty commits[] renders no <details> element', () => {
    const out = renderIndexHtml(
      { schema: 2, versions: [entry({ version: 'v1.0.0', commits: [] })] },
      repo,
    );
    expect(out).not.toContain('<details');
  });

  it('escapeHtml maps all HTML metacharacters', () => {
    expect(escapeHtml('&')).toBe('&amp;');
    expect(escapeHtml('<')).toBe('&lt;');
    expect(escapeHtml('>')).toBe('&gt;');
    expect(escapeHtml('"')).toBe('&quot;');
    expect(escapeHtml("'")).toBe('&#39;');
    expect(escapeHtml('<script>alert("x")</script>')).toBe(
      '&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;',
    );
  });

  it('escapes user-controlled version names in output', () => {
    const out = renderIndexHtml(
      { schema: 2, versions: [entry({ version: 'v1<script>' })] },
      repo,
    );
    expect(out).toContain('v1&lt;script&gt;');
    expect(out).not.toContain('v1<script>');
  });

  it('footer contains the freshness signal', () => {
    const out = renderIndexHtml({ schema: 2, versions: [] }, repo);
    expect(out).toContain('Generated by gh-pages-multiplexer');
  });
});

describe('full card rendering', () => {
  it('header h1 wraps an anchor to the GitHub repo with title "View on GitHub"', () => {
    const out = renderIndexHtml({ schema: 2, versions: [] }, repo);
    expect(out).toMatch(
      /<h1[^>]*>\s*<a[^>]*href="https:\/\/github\.com\/acme\/widgets"[^>]*title="View on GitHub"[^>]*>acme\/widgets<\/a>\s*<\/h1>/,
    );
  });

  it('renders <time datetime=...> with visible UTC format', () => {
    const out = renderIndexHtml(
      {
        schema: 2,
        versions: [entry({ version: 'v1.0.0', timestamp: '2026-04-06T12:00:00.000Z' })],
      },
      repo,
    );
    expect(out).toContain('<time');
    expect(out).toContain('datetime="2026-04-06T12:00:00.000Z"');
    expect(out).toMatch(/\d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC/);
  });

  it('renders short SHA link (7 chars) to GitHub commit URL in mono', () => {
    const fullSha = '1234567890abcdef1234567890abcdef12345678';
    const out = renderIndexHtml(
      { schema: 2, versions: [entry({ version: 'v1.0.0', sha: fullSha })] },
      repo,
    );
    expect(out).toContain(`href="https://github.com/acme/widgets/commit/${fullSha}"`);
    expect(out).toMatch(/class="mono"[^>]*href="https:\/\/github\.com\/acme\/widgets\/commit\/1234567890abcdef1234567890abcdef12345678"[^>]*>1234567<|href="https:\/\/github\.com\/acme\/widgets\/commit\/1234567890abcdef1234567890abcdef12345678"[^>]*class="mono"[^>]*>1234567</);
  });

  it('renders a View → link to ../{version}/', () => {
    const out = renderIndexHtml(
      { schema: 2, versions: [entry({ version: 'v1.0.0' })] },
      repo,
    );
    expect(out).toMatch(/href="\.\.\/v1\.0\.0\/"[^>]*>View \u2192<\/a>/);
  });

  it('singular commit copy for exactly 1 commit', () => {
    const out = renderIndexHtml(
      {
        schema: 2,
        versions: [
          entry({ version: 'v1.0.0', commits: [commit({ sha: 'abcdef1234567890' })] }),
        ],
      },
      repo,
    );
    expect(out).toContain('<summary>1 commit</summary>');
    expect(out).not.toContain('1 commits</summary>');
  });

  it('plural commit copy for 3 commits', () => {
    const out = renderIndexHtml(
      {
        schema: 2,
        versions: [
          entry({
            version: 'v1.0.0',
            commits: [
              commit({ sha: 'aaaaaaa0000000' }),
              commit({ sha: 'bbbbbbb0000000' }),
              commit({ sha: 'ccccccc0000000' }),
            ],
          }),
        ],
      },
      repo,
    );
    expect(out).toContain('<summary>3 commits</summary>');
  });

  it('commit row format: shortSha subject — authorName, subject is first line only', () => {
    const out = renderIndexHtml(
      {
        schema: 2,
        versions: [
          entry({
            version: 'v1.0.0',
            commits: [
              commit({
                sha: 'abcdef1234567890abcdef1234567890abcdef12',
                author_name: 'Alice',
                message: 'feat: thing\n\nbody line',
              }),
            ],
          }),
        ],
      },
      repo,
    );
    expect(out).toContain('abcdef1');
    expect(out).toContain('feat: thing');
    expect(out).toContain('\u2014 Alice');
    expect(out).not.toContain('body line');
  });
});

describe('CSS / theming', () => {
  const out = renderIndexHtml(
    { schema: 2, versions: [entry({ version: 'v1.0.0' })] },
    repo,
  );

  it('contains light theme tokens', () => {
    expect(out).toContain('--bg: #ffffff');
    expect(out).toContain('--fg: #1f2328');
    expect(out).toContain('--accent: #0969da');
  });

  it('contains dark theme via prefers-color-scheme media query', () => {
    expect(out).toContain('@media (prefers-color-scheme: dark)');
    expect(out).toContain('--bg: #0d1117');
  });

  it('contains mobile breakpoint at 600px', () => {
    expect(out).toContain('@media (max-width: 600px)');
  });

  it('has zero <script> tags', () => {
    expect(out.toLowerCase()).not.toContain('<script');
  });
});

describe('XSS mitigation', () => {
  it('escapes <script> payload in version name', () => {
    const payload = 'v1<script>alert(1)</script>';
    const out = renderIndexHtml(
      { schema: 2, versions: [entry({ version: payload })] },
      repo,
    );
    expect(out).not.toContain('<script>alert(1)</script>');
    expect(out).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
  });

  it('escapes img onerror payload in commit message', () => {
    const out = renderIndexHtml(
      {
        schema: 2,
        versions: [
          entry({
            version: 'v1.0.0',
            commits: [
              commit({
                sha: 'abcdef1234567890abcdef1234567890abcdef12',
                message: '<img src=x onerror=alert(1)>',
              }),
            ],
          }),
        ],
      },
      repo,
    );
    expect(out).not.toContain('<img src=x onerror=alert(1)>');
    expect(out).toContain('&lt;img src=x onerror=alert(1)&gt;');
  });

  it('escapes attribute-breaker payload in author name', () => {
    const out = renderIndexHtml(
      {
        schema: 2,
        versions: [
          entry({
            version: 'v1.0.0',
            commits: [
              commit({
                sha: 'abcdef1234567890abcdef1234567890abcdef12',
                author_name: '"><script>alert(1)</script>',
              }),
            ],
          }),
        ],
      },
      repo,
    );
    expect(out).not.toContain('"><script');
    expect(out).not.toContain('<script>alert(1)</script>');
    expect(out).toContain('&quot;&gt;&lt;script&gt;');
  });
});

describe('html-validate gate', () => {
  it('simple empty manifest passes html-validate', async () => {
    const out = renderIndexHtml({ schema: 2, versions: [] }, repo);
    await assertValidHtml(out);
  });

  it('realistic fixture with 2 versions passes html-validate', async () => {
    const out = renderIndexHtml(
      {
        schema: 2,
        versions: [
          entry({
            version: 'v2.0.0',
            sha: '1234567890abcdef1234567890abcdef12345678',
            timestamp: '2026-04-06T12:00:00.000Z',
            commits: [
              commit({
                sha: 'aaaaaaa1111111111111111111111111111111111',
                message: 'feat: add widget\n\nlong body',
                author_name: 'Alice',
              }),
              commit({
                sha: 'bbbbbbb2222222222222222222222222222222222',
                message: 'fix: bug',
                author_name: 'Bob',
              }),
              commit({
                sha: 'ccccccc3333333333333333333333333333333333',
                message: 'docs: readme',
                author_name: 'Carol',
              }),
            ],
          }),
          entry({
            version: 'v1.0.0',
            sha: '9999999999999999999999999999999999999999',
            timestamp: '2026-04-01T09:30:00.000Z',
          }),
        ],
      },
      { owner: 'brandon-fryslie', repo: 'ghpm-validation' },
    );
    await assertValidHtml(out);
  });
});

describe('renderRedirectHtml', () => {
  it('redirects to the latest non-PR version', () => {
    const manifest: Manifest = {
      schema: 2,
      versions: [
        entry({ version: 'pr-42', ref: 'refs/pull/42/merge' }),
        entry({ version: 'main', ref: 'refs/heads/main' }),
        entry({ version: 'v1.0.0', ref: 'refs/tags/v1.0.0' }),
      ],
    };
    const html = renderRedirectHtml(manifest);
    expect(html).toContain('url=./main/');
    expect(html).not.toContain('pr-42');
  });

  it('skips all PR versions to find the first non-PR', () => {
    const manifest: Manifest = {
      schema: 2,
      versions: [
        entry({ version: 'pr-1', ref: 'refs/pull/1/merge' }),
        entry({ version: 'pr-2', ref: 'refs/pull/2/merge' }),
        entry({ version: 'v2.0.0', ref: 'refs/tags/v2.0.0' }),
      ],
    };
    const html = renderRedirectHtml(manifest);
    expect(html).toContain('url=./v2.0.0/');
  });

  it('falls back to _versions/ when all versions are PRs', () => {
    const manifest: Manifest = {
      schema: 2,
      versions: [
        entry({ version: 'pr-1', ref: 'refs/pull/1/merge' }),
      ],
    };
    const html = renderRedirectHtml(manifest);
    expect(html).toContain('url=./_versions/');
  });

  it('falls back to _versions/ for empty manifest', () => {
    const html = renderRedirectHtml({ schema: 2, versions: [] });
    expect(html).toContain('url=./_versions/');
  });
});
